# Generated by Django 2.0.3 on 2018-04-28 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inthegram', '0002_auto_20180428_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='image',
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='inthegram.Post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='inthegram.Post'),
        ),
    ]
